"""refactor : route column Point->place

Revision ID: 09a8ae8a7a5d
Revises: e70ead17bc1a
Create Date: 2024-01-16 18:42:10.503020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09a8ae8a7a5d'
down_revision = 'e70ead17bc1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route', schema=None) as batch_op:
        batch_op.add_column(sa.Column('departure', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('arrival', sa.String(length=255), nullable=True))
        batch_op.drop_column('startX')
        batch_op.drop_column('endX')
        batch_op.drop_column('startY')
        batch_op.drop_column('endY')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route', schema=None) as batch_op:
        batch_op.add_column(sa.Column('endY', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('startY', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('endX', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('startX', sa.FLOAT(), nullable=True))
        batch_op.drop_column('arrival')
        batch_op.drop_column('departure')

    # ### end Alembic commands ###
