"""coordinate use

Revision ID: 2df51e19ff6a
Revises: f801ccff49bc
Create Date: 2024-01-05 14:29:39.695636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2df51e19ff6a'
down_revision = 'f801ccff49bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mark', schema=None) as batch_op:
        batch_op.drop_column('endY')
        batch_op.drop_column('endX')

    with op.batch_alter_table('object', schema=None) as batch_op:
        batch_op.drop_column('pointX')
        batch_op.drop_column('pointY')

    with op.batch_alter_table('pass_point', schema=None) as batch_op:
        batch_op.drop_column('pointX')
        batch_op.drop_column('pointY')

    with op.batch_alter_table('route', schema=None) as batch_op:
        batch_op.drop_column('endX')
        batch_op.drop_column('endY')
        batch_op.drop_column('startY')
        batch_op.drop_column('startX')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route', schema=None) as batch_op:
        batch_op.add_column(sa.Column('startX', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('startY', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('endY', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('endX', sa.FLOAT(), nullable=True))

    with op.batch_alter_table('pass_point', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pointY', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('pointX', sa.FLOAT(), nullable=True))

    with op.batch_alter_table('object', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pointY', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('pointX', sa.FLOAT(), nullable=True))

    with op.batch_alter_table('mark', schema=None) as batch_op:
        batch_op.add_column(sa.Column('endX', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('endY', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
