"""add BaseColumns

Revision ID: f801ccff49bc
Revises: 617eda7915a0
Create Date: 2024-01-05 10:47:16.301777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f801ccff49bc'
down_revision = '617eda7915a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('object', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=255), server_default='Active', nullable=False))
        batch_op.add_column(sa.Column('createAt', sa.DateTime(), nullable=False))

    with op.batch_alter_table('pass_point', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=255), server_default='Active', nullable=False))
        batch_op.add_column(sa.Column('createAt', sa.DateTime(), nullable=False))

    with op.batch_alter_table('route', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=255), server_default='Active', nullable=False))
        batch_op.add_column(sa.Column('createAt', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route', schema=None) as batch_op:
        batch_op.drop_column('createAt')
        batch_op.drop_column('status')

    with op.batch_alter_table('pass_point', schema=None) as batch_op:
        batch_op.drop_column('createAt')
        batch_op.drop_column('status')

    with op.batch_alter_table('object', schema=None) as batch_op:
        batch_op.drop_column('createAt')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
