"""delete passpoint

Revision ID: fe399ac389ad
Revises: 09a8ae8a7a5d
Create Date: 2024-01-27 11:26:23.913193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe399ac389ad'
down_revision = '09a8ae8a7a5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pass_point')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pass_point',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('route', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=255), server_default=sa.text("'Active'"), nullable=False),
    sa.Column('createAt', sa.DATETIME(), nullable=False),
    sa.Column('X', sa.FLOAT(), nullable=True),
    sa.Column('Y', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['route'], ['route.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
